# Generated by Django 4.0.1 on 2024-05-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_shipment_options_alter_shipment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
    ]
